<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Streetwear Republic | Contact Us</title>';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="container">';
echo '<div class="navbar">';
echo '<div class="logo">';
echo '<a href="index.html"><img src="images/logo.png" width="200px"></a>';
echo '</div>';
echo '<nav>';
echo '<ul id="MenuItems">';
echo '<li><a href="index.html">Home</a></li>';
echo '<li><a href="products.html">Products</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '<li><a href="account.html">Account</a></li>';
echo '</ul>';
echo '</nav>';
echo '<a href="cart.html"><img src="images/cart.png" width="30px" height="30px"></a>';
echo '<img src="images/menu.png" class="menu-icon" onclick="menutoggle()">';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- featured products -->';
echo '';
echo '<div class="small-container">';
echo '<div class="row row-2">';
echo '<h2>Contact Us</h2>';
echo '</div>';
echo '</div>';
echo '';
echo '<section class="contact-me">';
echo '<div class="row">';
echo '<div class="contact-col">';
echo '<div>';
echo '<span>';
echo '<h5>112 College Road</h5>';
echo '<p>Loch Sheldrake, NY 12759</p>';
echo '</span>';
echo '</div>';
echo '<div>';
echo '<span>';
echo '<h5>+1 (845)-123-4567</h5>';
echo '<p>Monday-Friday, 9AM to 5PM</p>';
echo '</span>';
echo '</div>';
echo '<div>';
echo '<span>';
echo '<h5>cg0123@sunysullivan.edu</h5>';
echo '<p>Email me for an inquiries</p>';
echo '</span>';
echo '</div>';
echo '</div>';
echo '<div class="contact-col">';
echo '<form action="">';
echo '<input type="text" placeholder="Enter your full name" required>';
echo '<input type="email" placeholder="Enter email address" required>';
echo '<input type="text" placeholder="Enter your subject" required>';
echo '<textarea rows="8" placeholder="Message" required></textarea>';
echo '<button type="sumbit" class="btn">Send Message</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="location">';
echo '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2975.9889067417093!2d-74.67105068442875!3d41.';
echo '763896979231454!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89dcbe959f43bc8d%3A0xcb0e7606a29b02c2!2sSUNY';
echo '%20Sullivan!5e0!3m2!1sen!2sus!4v1650824782859!5m2!1sen!2sus" width="600" height="450" style="border:0;"';
echo 'allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '</section>';
echo '';
echo '<!-- footer -->';
echo '';
echo '<div class="footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="footer-col-1">';
echo '<h3>Download Our App</h3>';
echo '<p>Download on Android and IOS devices.</p>';
echo '<div class="app-logo">';
echo '<img src="images/play-store.png">';
echo '<img src="images/app-store.png">';
echo '</div>';
echo '</div>';
echo '<div class="footer-col-2">';
echo '<img src="images/logo-white.png">';
echo '<p>Our goal is to create an aftermarket for both';
echo '<br>enthausist and newcomers to buy';
echo '<br>the latest and/or rarest sneakers in an authentic way.</p>';
echo '</div>';
echo '<div class="footer-col-3">';
echo '<h3>Useful Links</h3>';
echo '<ul>';
echo '<li>Coupons</li>';
echo '<li>Blog Post</li>';
echo '<li>Return Policy</li>';
echo '<li>Join Affiliate</li>';
echo '</ul>';
echo '</div>';
echo '<div class="footer-col-4">';
echo '<h3>Follow Us</h3>';
echo '<ul>';
echo '<li>Facebook</li>';
echo '<li>Instagram</li>';
echo '<li>Twitter</li>';
echo '<li>YouTube</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<hr>';
echo '<p class="copyright">&copy; Copyright 2022 - Streetwear Republic</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- js for toggle menu -->';
echo '';
echo '<script>';
echo 'var MenuItems = document.getElementById("MenuItems");';
echo '';
echo 'MenuItems.style.maxHeight = "0px";';
echo '';
echo 'function menutoggle() {';
echo 'if(MenuItems.style.maxHeight == "0px")';
echo '{';
echo 'MenuItems.style.maxHeight = "200px";';
echo '}';
echo 'else';
echo '{';
echo 'MenuItems.style.maxHeight = "0px"';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>
